databases:
  - name: course-db
    plan: free
    databaseName: course
    user: course

services:
  - type: web
    plan: free
    name: course
    runtime: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: DATABASE_URL
        fromDatabase:
          name: course-db
          property: connectionString
    numInstances: 1