databases:
  - name: course-db
    plan: free
    databaseName: course
    user: course
    
services:
  - type: web
    plan: free
    name: <NOME-SERVIÇO>
    runtime: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JDK_JAVA_OPTIONS
        value: -Xms256m -Xmx512m -Dspring.profiles.active=prod
    numInstances: 1